### PR TITLE
Allow partially colored class names

### PR DESCRIPTION
**Pull request by halcyo-n**
This NOP's what i assume is "UI_VerifyString" which is inlined within another func.
This allows for partially colored classes.
Example: C^1lass 1

It will not let you make a fully colored class such as "^1Class 1"

### CODE REVIEW

**Comment by Jemal** [comment]
What’s the point of this? Should just allow any kind of class names

**Comment by halcyo-n** [comment]
> What’s the point of this? Should just allow any kind of class names

Thats what it does, i patched out the "illegal character" check

**Comment by momo5502** [comment]
Please. Do not touch submodules...

**Comment by x-dev-urandom** [comment]
Please rebase just this commit https://github.com/XLabsProject/iw6x-client/pull/145/commits/0d4ba9340cd921d45c7e6990dba5f5b0bc5fc391 on top of develop to clean up this pull request.

**Comment by momo5502** [comment]
A partial fix is not a good fix.

**Comment by halcyo-n** [comment]
nigger

**Pull request closed without merging**
