### PR TITLE
Local File and Launcher support

### PR DESCRIPTION
**Pull request by TheSoliderror**
This allows the game exes to run in the launcher and in local game files like the exes. Meaning you can use the xlabs appdata exe for local file use as well as launcher use. This mainly for people that have trouble launching the new xlabs launcher. This would also mean create a download link on the GitHub so people that cannot use the launcher can still download the exe and play the game without the launcher. This pull request will also allow the exe be updated. If this pull goes through I recommend creating a updater for local file users so they can still get updates without the launcher. Perhaps using a batch file to update the exe. If I must I will create this as well.

### CODE REVIEW

**Comment by diamante0018** [comment]
Kekw

**Comment by JoniBrn** [comment]
merged

**Review by diamante0018 — CHANGES_REQUESTED** [review]
This should not be merged

**Comment by momo5502** [comment]
This defeats the purpose of the entire launcher environment.

**Pull request closed without merging**
