### PR TITLE
Fix precaching not working without a fast_restart

### PR DESCRIPTION
**Pull request by GEEKiDoS**

### CODE REVIEW

**Review by momo5502 — CHANGES_REQUESTED** [review]
Don't make the variable static.

**Review by momo5502 — COMMENTED** [review]
Would game::SV_Loaded() work instead?

**Comment by GEEKiDoS** [comment]
> Would game::SV_Loaded() work instead?

I didn't know that function

**Review by momo5502 — APPROVED** [review]
SV_Loaded and sv_runnint both get set in SV_SpawnServer, so they should be pretty much interchangable

**Pull request merged**
